default: &default
  adapter: postgresql
  pool: <%= ENV["DATABASE_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>
  encoding: unicode


development:
  <<: *default
  host: localhost
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: api_HOUZ_development

test:
  <<: *default
  host: localhost
  database: api_HOUZ_test
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>
